version: '2'
services:
    georeferenziazione-app:
        image: georeferenziazione
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@georeferenziazione-oracle:1521:georeferenziazione
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
